### PR TITLE
Sessions

### PR DESCRIPTION
**Pull request by kiarn**
First commit : possibility to configure max session duration, default to 3600s.
Since there's a conflict with importing `aj` in `session.py` ( conflict between `aj.config` the module and `aj.config` the property ), I pass the parameter in the Session constructor in `middleware.py`.

Second commit : show remaining time for the current session. Not very proud of the css, but it's always aligned with the hostname, even if the hostname is shorter ( tested with Chrome and firefox with many differents resolutions ).

### CODE REVIEW

**Comment by Eugeny** [comment]
LGTM, I'd just move the timer a bit closer to the hostname.
Another idea would be to hide the timer altogether until less than 30 minutes of the session are remaining.

**Comment by kiarn** [comment]
> I'd just move the timer a bit closer to the hostname.

Done.

> Another idea would be to hide the timer altogether until less than 30 minutes of the session are remaining.

The first commit let the possibility to configure session time. If this is lower than 30min, the session time would also appears on the login screen, so I add a test if `identity.user` is defined.
I can also complete with `&& counter[1] <= 30` if you want :)

**Comment by Eugeny** [comment]
Yes, I think adding a `resttime < 1800` (to account for hours) is good idea

**Comment by kiarn** [comment]
Done !

**Pull request merged**
