### PR TITLE
Vinogradov Dmitriy

### PR DESCRIPTION
**Pull request by EauDeVie**

### CODE REVIEW

**Comment by Eugeny** [comment]
I'm sorry, but we run our translations on Crowdin: https://crowdin.com/project/ajenti/ru#

**Comment by EauDeVie** [comment]
I understand, but part of the text you have not been translated. I just added the missingtranslation and corrected the words that were translated incorrectly.

**Comment by Eugeny** [comment]
I still can't merge your translations because they will be overwritten by the next Crowdin import. As much as I appreciate your work, you need to make the corrections on Crowdin instead.

**Comment by EauDeVie** [comment]
sorry for the time spent.  good luck in continuing


среда, 6 мая 2020 г., 00:10 +0300 от notifications@github.com  <notifications@github.com>:

**Pull request closed without merging**
