### PR TITLE
Suggestion to directly retrieve plugins infos from Pypi.

### PR DESCRIPTION
**Pull request by kiarn**
Hello @Eugeny ,

**This is not finished**, it's only a suggestion to get the plugins states from Pypi instead of http://ajenti.org/plugins/list. If you're ok with this method, I will finish it, or we can drop it and let the actual method.

Some notices about it : 

- it makes a request to https://pypi.org/simple and parses it with bs4, which introduces a dependency to bs4,
- then, it makes concurrent requests (Python3 !) for each plugin. This can also be made with angularjs
- it takes a long time to get the infos (more than 15s), that's why I introduce a check button to check it manually, and not when the page is loading.

What do you think about it ?

### CODE REVIEW

**Comment by Eugeny** [comment]
Looking good! You can improve parsing time dramatically by using lxml instead of bs4

**Comment by kiarn** [comment]
Ok, thanks for the hint, it's really impressive how much faster it is.
How do you check/calculate the fingerKey / signature for each plugin ?
This is used to check if a [plugin is official or not](https://github.com/ajenti/ajenti/blob/d9b5893c3037a4c583cf5ed94d636cc0dba20624/plugins/plugins/resources/js/controllers/index.controller.es#L50).

**Comment by Eugeny** [comment]
There's no way to do this without downloading the package - the PyPI API is unfortunately very limited :(

**Comment by kiarn** [comment]
Ok, in the last [commit](https://github.com/ajenti/ajenti/pull/1229/commits/ee0d202806e7a077328088658cb5dc55b7e8d50a) I tested it with the author_email which is pretty insecured.
Alternative is to list the official plugins hard coded (I mean the plugins in this repo). Not really beautiful, but it works :)
Other alternative : add a feature to ajenti-dev-multitool to scan and push automatically a list of official plugins at the root of the github account, e.g. `official_plugins.json`, each time when you run a `ajenti-dev-multitool --setuppy`. You are anyway the only one who can push it on this repo.
Then it's easy to request this json file, and it would always be automatically done.
Should I do this ?

**Comment by Eugeny** [comment]
Well, since me and you are the only ones who can make official plugins, you can just add a .txt list in the repo manually :)

**Comment by kiarn** [comment]
Done !

**Comment by Eugeny** [comment]
Cool - let me know when it's clear to merge

**Pull request merged**
