### PR TITLE
Changed gevent.coros to gevent.lock

### PR DESCRIPTION
**Pull request by nailujx86**
Otherwise it doesn't work for gevent version >= 1.0
https://github.com/ajenti/ajenti/issues/1002#issuecomment-271574322

Nobody should be using gevent < 1.0 anymore anyway

### CODE REVIEW

**Comment by hitech95** [comment]
The users running Debian Wheezy LTS have a older version of gevent and this broke the setup

**Comment by nailujx86** [comment]
@hitech95 Shouldn't
```
pip install -U gevent 
```
easily fix that? For me it did.

**Comment by hitech95** [comment]
Not exactly, it can install  but after the update it still have problems with other plugins that use the old version "gevent.coros".  I have spet a couple days tring to solve the problem. As a test I moved to ubuntu server LTS.

**Comment by nailujx86** [comment]
Maybe we should revert this change and fix the "bug" by applying the solution for example in the install script for just the users that have a higher version than 1.0 of Gevent installed? But I guess that would be an ugly solution.

**Comment by hitech95** [comment]
Maybe the inverse solution is the best one, keep the commit and add to the script the special case. Once the old LTS is dropped you can just remove the special case.

**Pull request merged**
