### PR TITLE
Fixs

### PR DESCRIPTION
**Pull request by kiarn**
- `dev_mode` was forgotten in `core.py`, there was no automatic build anymore,
- replacing post requests as get in filesystem to avoid empty bodies,
- replace overall `json` with `simplejson` and avoid some bytes/strings collisions in others systems or python versions,
- bump all + some little fixs.

### CODE REVIEW

**Comment by Eugeny** [comment]
What is the reason for simplejson replacement? Sounds like you just need to put `.decode()` in all the right places.

**Comment by Eugeny** [comment]
Also don't replace POST with GET because browsers are allowed to a) cache GET requests and b) re-execute them whenever they feel up to, e.g. when working with DevTools.

**Comment by kiarn** [comment]
> What is the reason for simplejson replacement? Sounds like you just need to put `.decode()` in all the right places.

It's only tu support python 3.5 in some cases : 

```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.loads(b'{}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
>>> json.loads('{}')
{}
################################################################
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.loads(b'{}')
{}
```

I didn't look exactly what the problem was, but I strongly suspect the `HttpContext` object.

> Also don't replace POST with GET because browsers are allowed to a) cache GET requests and b) re-execute them whenever they feel up to, e.g. when working with DevTools.

Ok, didn't know that, I can try to replace StringIO with BytesIO in the [cgi.Fieldstorage](https://github.com/ajenti/ajenti/blob/5919d6a1eb326fc1e2c17b911665627abc2db201/ajenti-core/aj/http.py#L139), but I have to retest all.

**Comment by Eugeny** [comment]
OK - got it.

**Comment by kiarn** [comment]
`cgi.Fieldstorage` use yet `BytesIO` and I'm pretty sure I was not able to test all, that's why I've added an [instance test to convert to bytes](https://github.com/ajenti/ajenti/blob/38cf4fd1f4ac4125dccc1983878fe78d4be8b318/ajenti-core/aj/http.py#L139) if needed.
It was necessary to modify filesystem upload for this.

For compatibility reason with PY3.5 ( Debian 9 ), I replaced all `json.loads(http_context.body)` with `json.loads(http_context.body.decode())` instead of using `simplejson`.

**Comment by 14159012** [comment]
* `devmo`تم نسيانها `core. لم يعد هناك بناء تلقائي ،
 * استبدال طلبات البريد عند دخول نظام الملفات لتجنب الأجسام الفارغة ،
> * استبدال عموما `jso`مع `simplejso`وتجنب بعض بايت / سلاسل التصادم في الأنظمة الأخرى أو الإصدارات الثعبان،
> * عثرة في جميع + بعض الإصلاحات الصغيرة.

**Pull request merged**
